#!/bin/sh

# This scripts selects the last integrity report generated by Tripwire and
# updates the database.

BIN=/usr/sbin/tripwire
DIR=/var/lib/tripwire/report
HOST=`hostname -s`
LAST_REPORT=`ls -1t $DIR/$HOST-*.twr | head -1`
$BIN --update --twrfile "$LAST_REPORT"
